Repository replay-framework/replay, pull requests merged in 2025-02, with the labels that each got.

#466 Actually remove deps
  framework/build.gradle
Labels: dependencies

#468 Expose flash keys ERROR and SUCCESS
  framework/src/play/mvc/Scope.java
Labels: enhancement, refactoring

#525 fastergt: remove `__reverseWithCheck*` methods from `ExecutableTemplates`
  fastergt/src/play/modules/gtengineplugin/gt_integration/GTJavaBase1xImpl.java
  fastergt/src/play/modules/gtengineplugin/gt_integration/GTPreCompiler1xImpl.java
  fastergt/src/play/templates/ExecutableTemplate.java
Labels: refactoring
